version: '3.1'
services:
  sentinel1:
    image: redis
    container_name: rds-sentinel-1
    ports:
    - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - ./conf/sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis
    container_name: rds-sentinel-2
    ports:
    - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - ./conf/sentinel2.conf:/usr/local/etc/redis/sentinel.conf

    sentinel3:
      image: redis
      container_name: rds-sentinel-3
      ports:
      - 26381:26379
      command: redis-sentinel /usr/local/etc/redis/sentinel.conf
      volumes:
      - ./conf/sentinel3.conf:/usr/local/etc/redis/sentinel.conf