version: '3'
services:
  pmaster:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pmaster
    ports:
      - 3306:3306
    networks:
      - pxcnet
    volumes:
      - pxcmaster:/var/lib/mysql
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
  pnode1:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pnode1
    ports:
      - 3307:3306
    networks:
      - pxcnet
    depends_on:
      - pmaster
    volumes:
      - pxcnode1:/var/lib/mysql
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "CLUSTER_JOIN=pmaster"
      - "TZ=Asia/Shanghai"
  pnode2: 
    image: percona/percona-xtradb-cluster:5.7
    container_name: pnode2
    ports:
      - 3308:3306
    networks:
      - pxcnet
    volumes:
      - pxcnode2:/var/lib/mysql
    depends_on:
      - pmaster
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "CLUSTER_JOIN=pmaster"
      - "TZ=Asia/Shanghai"

networks:
  pxcnet:
    driver: bridge

volumes:
  pxcmaster:
  pxcnode1:
  pxcnode2:

