version: '3'
services:
  master:
    image: percona/percona-xtradb-cluster:5.7
    container_name: dbmaster
    ports:
      - 3306:3306
    networks:
      - pxcnet
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "TZ=Asia/Shanghai"
  node1:
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxcnode1
    ports:
      - 3307:3306
    networks:
      - pxcnet
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "CLUSTER_JOIN=dbmaster"
      - "TZ=Asia/Shanghai"
  node2: 
    image: percona/percona-xtradb-cluster:5.7
    container_name: pxcnode2
    ports:
      - 3308:3306
    networks:
      - pxcnet
    environment:
      - "CLUSTER_NAME=dbcluster"
      - "XTRABACKUP_PASSWORD=root"
      - "CLUSTER_JOIN=dbmaster"
      - "TZ=Asia/Shanghai"

networks:
  pxcnet:
    driver: bridge
